name: Deploy to Arcade

permissions:
  contents: read

on:
  # Trigger on semver tags (e.g., v1.0.0, v2.1.3, v1.0.0-beta.1)
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+*

  # Trigger on GitHub releases
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: 3.13

      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          version: latest

      - name: Install dependencies
        run: |
          cd foundaudio
          make install

      - name: Deploy to Arcade
        env:
          ARCADE_API_KEY: ${{ secrets.ArcadeApiKey }}
        run: |
          cd foundaudio
          # Create arcade credentials directory and file for API key auth
          mkdir -p ~/.arcade
          cat > ~/.arcade/credentials.yaml << EOF
          cloud:
            api:
              key: $ARCADE_API_KEY
            user:
              email: rayjsmets@gmail.com
          EOF
          uv run arcade deploy --deployment-file ../worker.toml

      - name: Get deployment info
        env:
          ARCADE_API_KEY: ${{ secrets.ArcadeApiKey }}
        run: |
          cd foundaudio
          echo "Deployment completed for tag/release: ${{ github.ref_name }}"
          uv run arcade deploy status
